"""create users table in ariadne schema

Revision ID: e4c3b0d092b3
Revises: 
Create Date: 2025-08-10 14:31:10.467000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4c3b0d092b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('clinician', 'caretaker', 'admin', name='userrole'), nullable=False),
    sa.Column('child_diagnosis', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('account_create_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('content_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('messaging_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_engagement_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    schema='ariadne'
    )
    op.create_index(op.f('ix_ariadne_users_user_id'), 'users', ['user_id'], unique=False, schema='ariadne')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ariadne_users_user_id'), table_name='users', schema='ariadne')
    op.drop_table('users', schema='ariadne')
    # ### end Alembic commands ###
